http:
    client:
        ssl:
            trust-store: truststore.jks
            trust-store-password: changeit
javax:
    net:
        debug: all
jira:
    host: jira.cwc-apps.com
    issecure: false
    loadData: true
    port: 443
    project: ESB Software Development - New
    user: sreedhar.butta
    password: ENC(/9dPcGCaFj3yO2WIZhZ9sdMxTNZJO8wP)

management:
    endpoints:
        web:
            exposure:
                include: prometheus
server:
    port: 9092
spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        password: my_password
        url: jdbc:mysql://kpidb:3306/kpi_database
        username: root
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        hibernate:
            ddl-auto: update
